### ISSUE TITLE
Feedback Summary for Milestone 3

### ISSUE THREAD

**Issue by sweber15** [UBC-MDS/DSCI522_group315#35]
Priority 1:
**Model choice**:
- [x] Fix accuracy vs error in table 2 - Sarah

**Report**:
Topic: Use clearer labels for features rather than head_att. You don't want the reader to have to constantly cross-reference these.

- - [x]  Add abbreviation list (priority one) (Sam)

Topic: Labels should have appropriate capitalization and no underscores 
- Figure 1 - hard to read - seaborn heatmap as an alternative
- Figure 2 - move to after how we chose our features so there isn't as many graphs or find an alternative way to plot all the data.
- Figure 2 is well chosen overall but should have clearer labels (size, and use Winner=Red/Blue rather than Blue Winner=0/1. Colour key should be categorical rather than a gradient (perhaps colour red for red wins, blue for blue wins?)
- [x] Fix labels - Sam
- [x] Rearrange plot (break down into categories for one row) add a caption above. - Sam
- [x] Table 2 is almost perfect - just list fewer significant digits!-- Sarah

**Report Text**:
-Topic: Data introduction: list the features related to fight performance.
- [x]  The abbreviation table with name and description of each feature (priority 1)(Sam)

Topic: Results interpretation generally good, to improve:
- [x] Validation error looks lower at 5 features - explain why 8-11 was better overall. Update with the reason (training vs test acc.) - Subing

- [x] Text duplicated: "The criteria sets priority from high to low ranking effective Striking/Grappling, effective Striking/Grappling and cage/ring Control(The ABC MMA Rules Committee 2017)."- Subing

- Elaborate a bit more on the predictors that are heavily weighted that aren't Striking/Grappling performance.
- [x] Lack of data non-striking and grappling data . For example, we would like more data - ring control - where fighters were in the space etc - Subing

**Tests**:

- Download needs test, see previous issue #12 (quote below)
- [x] Download the file and test if the columns match - Sarah
- [x]  Update dependencies if necessary - Sarah
- [x]  Make sure to update usage description for download to include the 01_ script tag. - Sarah
- [x] Preprocess and EDA also need tests - Sam

- [x] - In Analysis, simplify paths by hard coding your train/test split file names and then just giving the path to those files as one input parameter. - Sarah

- [x] Sam make changes on make script

### Priority 2:

** Report**
- Use clearer labels for features rather than head_att. You don't want the reader to have to constantly cross-reference these.
- [ ]  Program new names into the code - Sarah

- [x] Be more specific/detailed in your critique of the analysis and how you would improve and optimize the model. Discuss data limitatons - Sarah

### Priority 3: 
**Code**:

- [ ]  try and create more functions to modularize code. e.g. instead of having headers, it would make sense to have functions (priority 3)

**Model choice**:

- [ ] try more models (e.g. adabost), do we get the same results? (priority 3)
- [ ] does it make sense to have RFE? The judges see and should consider all of these factors. (priority 3).
- [ ] Include ROC curve, f1 score etc. (priority 3)

**Bash script**:
- [ ] put some echo lines in there to let the user know what they are doing. (priority 3).

Priority 1 - needs to be complete by Saturday at 6am
Priority 2 - should be complete by Saturday at 6am, but drop if necessary
Priority 3- lowest priority complete if time available_

**Comment by SamEdwardes** [comment]
Completed the make file. Please let me know if you make any changes to script arguments so I can update Makefile accordingly. See PR (#36).

**Comment by SamEdwardes** [comment]
Also added test to script 2 and 3. See PR (#36).

**Comment by SamEdwardes** [comment]
Added abbreviation table. See PR #36.

**Comment by SamEdwardes** [comment]
Improved scatter/box plot it only has 1 row and made the y axis labels more clear (PR #36).

**Comment by sweber15** [comment]
I updated feedback list to rank in order of priorities.

**Comment by sweber15** [comment]
Fixes in PR #37 

ML Analysis Script:
Cleaned up input paths to one input path to the preprocessed data and hard code the csv files
Reduced Table 2 to only have 4 decimal places
Cleaned up error plot with proper titles
Added tests for the ones removed

Updated makefile with change of inputs for ml script. 

Added tests in download data for input of url and output as csv file
Updated usage description

Updated readme with new dependencies for:

- test_that 2.2.1
- tidyselect  1.3.0
- tidyverse 1.1.0

Updated report with a few sentences on the bottom describing further ways to optimize our model

Add facet wrap heading titles to EDA script

**Comment by sweber15** [comment]
Priority 2 Update: Program new names into the code

I got the faceted plots working, but not the weights.csv or the correlation plot. 

For the faceted plots I used: 

 `  variable_names <- c(
    'sig_str_att' = "Sig. Strikes Attempted",
    'sig_str_landed'= "Sig. Strikes Landed",
    'sig_str_pct' = "Sig. Strikes Percent",
    'total_str_att'  = "Total Strikes Attempted",
    'total_str_landed' = "Total Strikes Landed",
    'td_att' = "Takedown Attempted",
    'td_landed' = "Takedowns Landed",
    'td_pct' = "Successful Takedown Percent",
    'sub_att' = "Submissions Attempted",
    'pass' = "Passes Attempted",
    'rev' = "Reversals",
    'head_att' = "Head Strikes Attempted",
    'head_landed' = "Head Strikes Landed",
    'body_att' = "Body Strikes Attempted",
    'body_landed' = "Body Strikes Lanaded",
    'leg_att' = "Leg Strikes Attempted",
    'leg_landed' = "Leg Strikes Landed",
    'distance_att' = "Strikes Attempted from Distance",
    'distance_landed' = "Strikes Landed from Distance",
    'clinch_att' = "Strikes Attempted from Clinch",
    'clinch_landed' = "Strikes Landed from Clinch",
    'ground_att' = "Strikes Attempted from Ground",
    'ground_landed' = "Strikes Landed from Ground"
  )
  `
Reassign as name
`  idx <- match(df$name, names(variable_names))
  df$names2 <- variable_names[idx]`

Then include as a labeller on the facet plots
`facet_wrap(~names2, nrow=1, labeller = labeller(name = variable_names,
               names2 = label_wrap_gen(10)))`

It seems to only work for the facetted plot, so I made those changes. As much as I would like to update the rest, I don't think it is feasible. 

Do you have any thoughts, team?
